export const ROUTE_NAMES = {
  HOME: "/",
  GAME: "/games",
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  USER_GAME: "/user/games",
  USER_GAME_ADD: "/user/games/add",
  USER_GAME_EDIT: "/user/games/edit",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_REGISTER: "/admin/register",
  ADMIN_LOGOUT: "/admin/logout",
  ADMIN_GAME: "/admin/games",
  ADMIN_GAME_ADD: "/admin/games/add",
  ADMIN_GAME_EDIT: "/admin/games/edit",
};
